import { describe, it, expect, vi, afterEach } from "vitest";
import { createPlayerChrome } from "../apps/web/src/features/playback/use-player-chrome";
afterEach(() => vi.useRealTimers());
describe("player chrome", () => {
  it("desktop hover stays visible while inside and hides on leave without hiding cursor", () => {
    vi.useFakeTimers();
    const c = createPlayerChrome();
    c.pointerEnter();
    vi.advanceTimersByTime(10000);
    expect(c.visible.value).toBe(true);
    c.pointerLeave();
    expect(c.visible.value).toBe(false);
    expect(c.hideCursor.value).toBe(false);
    c.dispose();
  });
  it("fullscreen hides exactly at five seconds and activity restarts deadline", () => {
    vi.useFakeTimers();
    const c = createPlayerChrome();
    c.setFullscreen(true);
    vi.advanceTimersByTime(4999);
    expect(c.visible.value).toBe(true);
    vi.advanceTimersByTime(1);
    expect(c.visible.value).toBe(false);
    expect(c.hideCursor.value).toBe(true);
    c.activity();
    vi.advanceTimersByTime(4000);
    c.activity();
    vi.advanceTimersByTime(4999);
    expect(c.visible.value).toBe(true);
    c.setFullscreen(false);
    expect(c.hideCursor.value).toBe(false);
    c.dispose();
  });
  it("menus, dragging and keyboard focus suspend hiding independently", () => {
    vi.useFakeTimers();
    const c = createPlayerChrome();
    c.setFullscreen(true);
    c.setMenuOpen(true);
    c.setDragging(true);
    vi.advanceTimersByTime(6000);
    c.setMenuOpen(false);
    vi.advanceTimersByTime(6000);
    expect(c.visible.value).toBe(true);
    c.setDragging(false);
    c.setKeyboardFocus(true);
    vi.advanceTimersByTime(6000);
    expect(c.visible.value).toBe(true);
    c.setKeyboardFocus(false);
    vi.advanceTimersByTime(5000);
    expect(c.visible.value).toBe(false);
    c.dispose();
  });
  it("touch surface toggles, page hiding clears timers, dispose leaves no timer", () => {
    vi.useFakeTimers();
    const c = createPlayerChrome(true);
    c.toggleFromSurface();
    expect(c.visible.value).toBe(true);
    c.toggleFromSurface();
    expect(c.visible.value).toBe(false);
    c.toggleFromSurface();
    c.setPageHidden(true);
    expect(vi.getTimerCount()).toBe(0);
    c.setPageHidden(false);
    vi.advanceTimersByTime(5000);
    expect(c.visible.value).toBe(false);
    c.activity();
    c.dispose();
    expect(vi.getTimerCount()).toBe(0);
  });
});
