CREATE TABLE users (id uuid PRIMARY KEY, username text UNIQUE NOT NULL, password_hash text NOT NULL, admin boolean NOT NULL DEFAULT false);
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE rooms (id uuid PRIMARY KEY, name text NOT NULL, owner_id uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE room_members (room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), PRIMARY KEY(room_id,user_id));
CREATE TABLE room_snapshots (room_id uuid PRIMARY KEY REFERENCES rooms(id) ON DELETE CASCADE, state jsonb NOT NULL);
CREATE TABLE room_events (room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, revision bigint NOT NULL, state jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(room_id,revision));
CREATE TABLE command_results (room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, command_id uuid NOT NULL, user_id uuid REFERENCES users(id), state jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(room_id,command_id));
CREATE TABLE invites (token_hash text PRIMARY KEY, room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, revoked boolean NOT NULL DEFAULT false);
CREATE TABLE chat_messages (id uuid PRIMARY KEY, room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sources (id uuid PRIMARY KEY, name text NOT NULL, kind text NOT NULL CHECK(kind IN ('local','http','jellyfin','emby','agent')), config_encrypted text NOT NULL);
CREATE TABLE media_items (id uuid PRIMARY KEY, source_id uuid REFERENCES sources(id), title text NOT NULL, resource text NOT NULL, duration_ms double precision, metadata jsonb NOT NULL DEFAULT '{}', UNIQUE(source_id,resource));
CREATE TABLE media_tracks (id uuid PRIMARY KEY, media_id uuid REFERENCES media_items(id), kind text NOT NULL, metadata jsonb NOT NULL);
CREATE TABLE playlist_items (id uuid PRIMARY KEY, room_id uuid REFERENCES rooms(id) ON DELETE CASCADE, media_id uuid REFERENCES media_items(id), sort_order bigint NOT NULL);
CREATE TABLE agents (id uuid PRIMARY KEY, name text NOT NULL, token_hash text UNIQUE, pair_hash text UNIQUE, pair_expires_at timestamptz, revoked boolean NOT NULL DEFAULT false, last_seen timestamptz);
CREATE TABLE playback_sessions (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), room_id uuid REFERENCES rooms(id), media_id uuid REFERENCES media_items(id), generation bigint NOT NULL, delivery_token_hash text UNIQUE NOT NULL, resource jsonb NOT NULL, expires_at timestamptz NOT NULL, stopped boolean NOT NULL DEFAULT false);
CREATE TABLE media_jobs (id uuid PRIMARY KEY, session_id uuid REFERENCES playback_sessions(id), status text NOT NULL CHECK(status IN ('queued','running','succeeded','failed','cancelled')), spec jsonb NOT NULL, lease_until timestamptz, owner_id uuid, error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cache_entries (cache_key text PRIMARY KEY, path text NOT NULL, size_bytes bigint NOT NULL DEFAULT 0, last_used timestamptz NOT NULL DEFAULT now());
CREATE TABLE agent_transfers (id uuid PRIMARY KEY, agent_id uuid REFERENCES agents(id), token_hash text UNIQUE NOT NULL, request jsonb NOT NULL, claimed boolean NOT NULL DEFAULT false, expires_at timestamptz NOT NULL);
CREATE INDEX session_expiry ON sessions(expires_at);
CREATE INDEX jobs_claim ON media_jobs(status,lease_until);
CREATE INDEX playback_expiry ON playback_sessions(expires_at);
