import type { createPlaybackRuntime } from "../../playback/playback-runtime";

type PlaybackRuntime = ReturnType<typeof createPlaybackRuntime>;
/** Explicit allowlist: adding owner internals never enlarges the page surface. */
const pageFields = [
  "runPlayback",
  "distributedFacts",
  "peerStats",
  "peerSharing",
  "useDistributedOutput",
  "useOriginalSource",
  "startPeerSharing",
  "stopPeerSharing",
  "waiting",
  "blocked",
  "dragging",
  "mode",
  "nativePlatform",
  "nativePlaybackMode",
  "nativeEncodedHeight",
  "nativeLadderRenditions",
  "upstreamMeasuredOutput",
  "upstreamMeasuredMatchesRequested",
  "live",
  "nativeProvider",
  "nativeCredentialMode",
  "nativeQualityMaxHeight",
  "nativeQualityOptions",
  "nativeQualitySelectedHeight",
  "selectNativeQuality",
  "platformSubtitleTracks",
  "platformSubtitleId",
  "platformSubtitleStatus",
  "platformDanmakuStatus",
  "platformDanmakuEnabled",
  "platformDanmakuCues",
  "platformTextError",
  "platformTextLive",
  "platformLiveDanmakuMode",
  "setPlatformLiveDanmaku",
  "selectPlatformSubtitle",
  "setPlatformDanmaku",
  "tracks",
  "subtitles",
  "audioIndex",
  "subtitleIndex",
  "advancedCapabilities",
  "advancedFacts",
  "staticHlsFallbackEnabled",
  "staticHlsAvailability",
  "staticHlsAvailabilityText",
  "localHlsLadderEnabled",
  "ladderCapabilities",
  "ladderFacts",
  "ladderQuality",
  "ladderSelected",
  "ladderManual",
  "selectLadderQuality",
  "toneMapHdr",
  "burnInSubtitleIndex",
  "duration",
  "position",
  "sessionId",
  "preparation",
  "loadingStage",
  "startupDiagnostics",
  "cancelPreparation",
  "recoveryState",
  "playbackSummary",
  "recoveryLabel",
  "loadMedia",
  "enablePlayback",
  "applySubtitles",
  "attach",
] as const;
type PlaybackPageView = Pick<PlaybackRuntime, (typeof pageFields)[number]>;

/** Existing page aliases only; owner effects stay private. Each alias retires
 * with its consumer migration in docs/design/ROOM_RUNTIME_BOUNDARIES.md. */
export function createRoomPlaybackFacade(
  playback: PlaybackRuntime,
): PlaybackPageView {
  return Object.fromEntries(
    pageFields.map((key) => [key, playback[key]]),
  ) as PlaybackPageView;
}
