#!/usr/bin/env python3
"""Generate owned RST1 pixels, encode H.264, decode evidence, retain provenance.

Uses installed Pillow/FFmpeg only. No network, browser, service or credentials.
Output must not exist. All media and glyphs are generated by this source.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import sys
import zlib

from PIL import Image, ImageDraw
import PIL

# Independently specified 5x7 glyph rows, not imported from the decoder.
FONT = {
    '0': ['01110', '10001', '10011', '10101', '11001', '10001', '01110'],
    '1': ['00100', '01100', '00100', '00100', '00100', '00100', '01110'],
    '2': ['01110', '10001', '00001', '00010', '00100', '01000', '11111'],
    '3': ['11110', '00001', '00001', '01110', '00001', '00001', '11110'],
    '4': ['00010', '00110', '01010', '10010', '11111', '00010', '00010'],
    '5': ['11111', '10000', '10000', '11110', '00001', '00001', '11110'],
    '6': ['01110', '10000', '10000', '11110', '10001', '10001', '01110'],
    '7': ['11111', '00001', '00010', '00100', '01000', '01000', '01000'],
    '8': ['01110', '10001', '10001', '01110', '10001', '10001', '01110'],
    '9': ['01110', '10001', '10001', '01111', '00001', '00001', '01110'],
    ':': ['00000', '00100', '00100', '00000', '00100', '00100', '00000'],
    '.': ['00000', '00000', '00000', '00000', '00000', '00100', '00100'],
}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def info(path, root):
    return {'path': str(path.relative_to(root)), 'sha256': sha(path), 'bytes': path.stat().st_size}


def time_text(ms):
    return f'{ms // 3600000:02d}:{ms // 60000 % 60:02d}:{ms // 1000 % 60:02d}.{ms % 1000:03d}'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--frames', type=int, default=50)
    parser.add_argument('--fps', type=int, default=25)
    parser.add_argument('--origin-ms', type=int, default=0)
    args = parser.parse_args()
    if not (1 <= args.frames <= 1800 and 1 <= args.fps <= 60 and 0 <= args.origin_ms <= 359999999):
        parser.error('bounds: frames 1..1800, fps 1..60, origin-ms 0..359999999')
    timestamp = lambda n: args.origin_ms + (2 * n * 1000 + args.fps) // (2 * args.fps)
    if timestamp(args.frames - 1) > 359999999:
        parser.error('last timestamp exceeds two-digit hour range')
    root = args.output.resolve()
    os.umask(0o077)
    root.mkdir(parents=True, exist_ok=False)
    for name in ('source', 'decoded'):
        (root / name).mkdir()
    here = Path(__file__).resolve().parent
    sources = {p.name: sha(p) for p in (Path(__file__).resolve(), here / 'acceptance-timecode.mjs')}
    spec = {'format': 'RST1', 'width': 640, 'height': 360, 'fps': args.fps,
            'frame_count': args.frames, 'media_origin_ms': args.origin_ms,
            'generator_sha256': sources[Path(__file__).name]}
    sample_id = hashlib.sha256(json.dumps(spec, sort_keys=True, separators=(',', ':')).encode()).hexdigest()[:16]
    source_frames = []
    for frame in range(args.frames):
        ms = timestamp(frame)
        body = b'RST1' + bytes.fromhex(sample_id) + struct.pack('>IQHH', frame, ms, args.fps, 0)
        payload = body + struct.pack('>I', zlib.crc32(body))
        assert len(payload) == 32
        image = Image.new('RGB', (640, 360), (30, 50, 70))
        draw = ImageDraw.Draw(image)
        draw.rectangle((24, 24, 327, 135), fill='white')
        for row in range(12):
            for col in range(36):
                if 2 <= row <= 9 and 2 <= col <= 33:
                    n = (row - 2) * 32 + col - 2
                    bit = (payload[n // 8] >> (7 - n % 8)) & 1
                elif row == 1 and 1 <= col <= 34:
                    bit = col % 2
                elif row == 10 and 1 <= col <= 34:
                    bit = 1 - col % 2
                else:
                    bit = int(2 <= row <= 9 and col == 34)
                x, y = 32 + col * 8, 32 + row * 8
                draw.rectangle((x, y, x + 7, y + 7), fill='black' if bit else 'white')
        draw.rectangle((24, 152, 327, 195), fill='white')
        text = time_text(ms)
        for i, char in enumerate(text):
            for row, pixels in enumerate(FONT[char]):
                for col, bit in enumerate(pixels):
                    if bit == '1':
                        x, y = 32 + i * 24 + col * 4, 160 + row * 4
                        draw.rectangle((x, y, x + 3, y + 3), fill='black')
        # Simple authored moving patch gives the clip visible movement as well.
        x = 24 + (frame * 7) % 560
        draw.rectangle((x, 240, x + 31, 271), fill=(230, 180, 35))
        path = root / 'source' / f'{frame:06d}.png'
        image.save(path)
        source_frames.append({**info(path, root), 'frame_index': frame,
                              'original_position_ms': ms, 'human_readable': text,
                              'payload_hex': payload.hex()})
    commands = []

    def run(argv):
        commands.append(argv)
        result = subprocess.run(argv, check=True, capture_output=True, text=True, timeout=180)
        if result.stderr:
            (root / f'command-{len(commands):02d}.stderr.txt').write_text(result.stderr)
        return result.stdout

    ffmpeg_version = run(['ffmpeg', '-version'])
    ffprobe_version = run(['ffprobe', '-version'])
    run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-nostdin', '-n',
         '-threads', '1', '-framerate', str(args.fps), '-start_number', '0',
         '-i', str(root / 'source' / '%06d.png'), '-frames:v', str(args.frames),
         '-an', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '18',
         '-threads', '1', '-pix_fmt', 'yuv420p', '-g', str(args.fps),
         '-movflags', '+faststart', str(root / 'fixture.mp4')])
    probe_text = run(['ffprobe', '-v', 'error', '-select_streams', 'v:0',
                      '-show_streams', '-show_frames', '-show_entries',
                      'frame=best_effort_timestamp_time,pkt_duration_time:stream=codec_name,width,height,pix_fmt,r_frame_rate,avg_frame_rate,time_base,nb_frames',
                      '-of', 'json', str(root / 'fixture.mp4')])
    (root / 'ffprobe.json').write_text(probe_text)
    probe = json.loads(probe_text)
    frames = probe['frames']
    assert len(frames) == args.frames, 'encoded frame count changed'
    assert probe['streams'][0]['codec_name'] == 'h264'
    run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-nostdin', '-n',
         '-threads', '1', '-i', str(root / 'fixture.mp4'), '-map', '0:v:0',
         '-fps_mode', 'passthrough', '-pix_fmt', 'rgb24', '-threads', '1',
         '-start_number', '0', str(root / 'decoded' / '%06d.png')])
    decoded_frames = []
    for n, frame in enumerate(frames):
        pts = float(frame['best_effort_timestamp_time']) * 1000
        residual = abs(pts - n * 1000 / args.fps)
        assert residual <= 0.1, 'encoded PTS unexpectedly changed'
        decoded_frames.append({**info(root / 'decoded' / f'{n:06d}.png', root),
                               'frame_index': n, 'encoded_pts_ms': pts,
                               'pts_rounding_residual_ms': residual})
    manifest = {
        'schema_version': 1, 'scope': 'owned-fixture-codec-validation',
        'accepted': False, 'release_ready': False, 'sample_id': sample_id,
        'spec': spec, 'authorization': 'Original procedural pixels and numeric glyphs; no third-party media',
        'sources_sha256': sources, 'actual_command': [sys.executable, *sys.argv],
        'working_directory': str(Path.cwd()), 'commands': commands,
        'tools': {'ffmpeg': ffmpeg_version, 'ffprobe': ffprobe_version,
                  'python': sys.version, 'pillow': PIL.__version__},
        'media': info(root / 'fixture.mp4', root), 'probe': info(root / 'ffprobe.json', root),
        'source_frames': source_frames, 'decoded_frames': decoded_frames,
        'decoder_config': {'sampleId': sample_id, 'mediaOriginMs': args.origin_ms,
                           'fps': args.fps, 'frameCount': args.frames,
                           'screenshotWidth': 640, 'screenshotHeight': 360,
                           'roi': {'x': 0, 'y': 0, 'width': 640, 'height': 360}, 'scale': 1},
        'uncertainty': {'frame_duration_ms': 1000 / args.fps,
                        'timestamp_rounding_bound_ms': 0 if 1000 % args.fps == 0 else 0.5,
                        'maximum_observed_pts_residual_ms': max(f['pts_rounding_residual_ms'] for f in decoded_frames),
                        'browser_capture_or_clock_uncertainty_measured': False},
    }
    (root / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(json.dumps({'manifest': str(root / 'manifest.json'), 'sample_id': sample_id,
                      'frames': args.frames, 'accepted': False}))


if __name__ == '__main__':
    main()
