[package]
name = "persistence"
version.workspace = true
edition.workspace = true
[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
sqlx.workspace = true
protocol.workspace = true
media-core.workspace = true
room-core.workspace = true
sha2 = "0.10"
hex = "0.4"
